name: 'Inspector'
description: 'Checks if files and folders structure of the project follow kebab-case style'
inputs:
  token:
    description: 'GitHub token'
    required: true
  sources:
    description: 'String with folders to watch separated by commas'
    required: false
  exclude:
    description: 'String with folders or files to exclude from watch'
    required: false
  release_branches:
    description: 'String with branches to watch separated by commas'
    required: false
runs:
  using: 'node12'
  main: 'dist/index.js'
branding:
  icon: check-circle
  color: green
